### ISSUE TITLE
Create main page layout

### ISSUE THREAD

**Issue by joserigel** [HomeworkTracker/homework-tracker-frontend#2]
__Acceptance Criteria:__
- Add Navbar
- Add Columns based on Subjects

**Comment by dolapojohnson** [comment]
I'd like to contribute

**Comment by joserigel** [comment]
> I'd like to contribute

Hi, we're currently not set up to receive external contribution and very early at this stage for concepting, please do contact us when we have further progress to discuss. Thank you for your interest!

**Comment by joserigel** [comment]
No linked branch? @len06

**Comment by joserigel** [comment]
Done
